// ─────────────────────────────────────────────────────────────────────────────
// Mock data for development — replace with Prisma queries when DB is connected
// All values are realistic for a Ko Samui marina business
// ─────────────────────────────────────────────────────────────────────────────

// Re-export session 7–11 data
export {
  mockInventoryItems, mockStockMovements, mockPurchaseRequests,
  mockStaff, mockStaffTasks,
  mockIncidents,
} from "./mock-data-extra"

export const mockCustomers = [
  {
    id: "cust-001",
    customerType: "PRIVATE_OWNER",
    firstName: "James",
    lastName: "Thornton",
    companyName: null,
    nationality: "British",
    phone: "+66 81 234 5678",
    email: "j.thornton@email.com",
    address: "14/2 Moo 5, Bophut, Ko Samui, Surat Thani 84320",
    taxId: null,
    passportId: "GB123456789",
    preferredLanguage: "en",
    paymentTerms: 30,
    creditLimit: 500000,
    status: "ACTIVE",
    riskFlag: false,
    notes: "Long-term client since 2021. Prefers email communication.",
    createdAt: "2021-03-15T08:00:00Z",
    updatedAt: "2026-04-10T10:30:00Z",
    boatCount: 2,
    outstandingBalance: 31779,
  },
  {
    id: "cust-002",
    customerType: "CHARTER_OPERATOR",
    firstName: null,
    lastName: null,
    companyName: "Samui Blue Horizon Charter Co., Ltd.",
    nationality: "Thai",
    phone: "+66 77 456 7890",
    email: "ops@bluehorizon.co.th",
    address: "88/4 Nathon Pier Road, Ko Samui",
    taxId: "0105561234567",
    passportId: null,
    preferredLanguage: "th",
    paymentTerms: 15,
    creditLimit: 2000000,
    status: "ACTIVE",
    riskFlag: false,
    notes: "Major charter operator. Fleet of 4 vessels. Monthly billing.",
    createdAt: "2020-08-01T08:00:00Z",
    updatedAt: "2026-05-01T09:15:00Z",
    boatCount: 4,
    outstandingBalance: 352360,
  },
  {
    id: "cust-003",
    customerType: "PRIVATE_OWNER",
    firstName: "Sopida",
    lastName: "Charoenwong",
    companyName: null,
    nationality: "Thai",
    phone: "+66 89 765 4321",
    email: "sopida.c@gmail.com",
    address: "Ko Samui, Surat Thani",
    taxId: null,
    passportId: null,
    preferredLanguage: "th",
    paymentTerms: 30,
    creditLimit: 200000,
    status: "ACTIVE",
    riskFlag: false,
    notes: null,
    createdAt: "2022-11-20T08:00:00Z",
    updatedAt: "2026-03-05T14:00:00Z",
    boatCount: 1,
    outstandingBalance: 0,
  },
  {
    id: "cust-004",
    customerType: "PRIVATE_OWNER",
    firstName: "Erik",
    lastName: "Lindström",
    companyName: null,
    nationality: "Swedish",
    phone: "+66 83 111 2233",
    email: "erik.l@scandinavian-sailing.se",
    address: "c/o Samui Marina, Ko Samui",
    taxId: null,
    passportId: "SE987654321",
    preferredLanguage: "en",
    paymentTerms: 30,
    creditLimit: 300000,
    status: "ACTIVE",
    riskFlag: false,
    notes: "Sails from Sweden annually. Usually arrives Oct-Apr.",
    createdAt: "2023-01-10T08:00:00Z",
    updatedAt: "2026-01-20T11:00:00Z",
    boatCount: 1,
    outstandingBalance: 29425,
  },
  {
    id: "cust-005",
    customerType: "SPEEDBOAT_OPERATOR",
    firstName: null,
    lastName: null,
    companyName: "Samui Fast Boat Services",
    nationality: "Thai",
    phone: "+66 77 333 4455",
    email: "info@samuifastboat.com",
    address: "Nathon Pier, Ko Samui",
    taxId: "0105561234999",
    passportId: null,
    preferredLanguage: "th",
    paymentTerms: 7,
    creditLimit: 500000,
    status: "ACTIVE",
    riskFlag: false,
    notes: "Speedboat transfer operator. High frequency usage of ramp.",
    createdAt: "2021-06-01T08:00:00Z",
    updatedAt: "2026-04-22T08:30:00Z",
    boatCount: 3,
    outstandingBalance: 0,
  },
  {
    id: "cust-006",
    customerType: "PRIVATE_OWNER",
    firstName: "Michael",
    lastName: "Chen",
    companyName: null,
    nationality: "Australian",
    phone: "+66 86 999 8877",
    email: "m.chen@outlook.com",
    address: "Chaweng Beach Road, Ko Samui",
    taxId: null,
    passportId: "AU44556677",
    preferredLanguage: "en",
    paymentTerms: 30,
    creditLimit: 150000,
    status: "INACTIVE",
    riskFlag: false,
    notes: "Sold boat in March 2026. May return.",
    createdAt: "2022-03-15T08:00:00Z",
    updatedAt: "2026-03-20T08:00:00Z",
    boatCount: 0,
    outstandingBalance: 0,
  },
]

export const mockBoats = [
  {
    id: "boat-001",
    ownerId: "cust-001",
    ownerName: "James Thornton",
    name: "Sea Hawk",
    boatType: "MOTOR_YACHT",
    usageType: "private",
    brand: "Sunseeker",
    model: "Manhattan 52",
    yearBuilt: 2018,
    registrationNumber: "TH-KS-2021-001",
    hin: "SSK52ABC2018",
    flag: "Thailand",
    loaFt: 52.0,
    beamFt: 15.2,
    draftFt: 4.5,
    weightT: 18.5,
    hullMaterial: "fiberglass",
    engineType: "inboard",
    engineBrand: "Volvo Penta",
    numEngines: 2,
    fuelType: "diesel",
    trailerRequired: false,
    insuranceExpiry: "2026-08-31",
    status: "IN_WATER",
    currentLocationCode: "WB-A01",
    notes: "AC servicing due June 2026.",
    createdAt: "2021-03-15T08:00:00Z",
  },
  {
    id: "boat-002",
    ownerId: "cust-001",
    ownerName: "James Thornton",
    name: "Night Star",
    boatType: "SAILING_YACHT",
    usageType: "private",
    brand: "Beneteau",
    model: "Oceanis 45",
    yearBuilt: 2015,
    registrationNumber: "TH-KS-2022-014",
    hin: "BEN45XYZ2015",
    flag: "Thailand",
    loaFt: 45.0,
    beamFt: 14.4,
    draftFt: 6.2,
    weightT: 9.8,
    hullMaterial: "fiberglass",
    engineType: "inboard",
    engineBrand: "Yanmar",
    numEngines: 1,
    fuelType: "diesel",
    trailerRequired: false,
    insuranceExpiry: "2026-11-15",
    status: "IN_STORAGE",
    currentLocationCode: "DS-C03",
    notes: "Mast removed for storage.",
    createdAt: "2022-05-10T08:00:00Z",
  },
  {
    id: "boat-003",
    ownerId: "cust-002",
    ownerName: "Samui Blue Horizon Charter Co.",
    name: "Blue Dream",
    boatType: "CATAMARAN",
    usageType: "charter",
    brand: "Leopard",
    model: "45",
    yearBuilt: 2020,
    registrationNumber: "TH-KS-2020-088",
    hin: "LEO45BLU2020",
    flag: "Thailand",
    loaFt: 45.0,
    beamFt: 25.3,
    draftFt: 3.9,
    weightT: 11.2,
    hullMaterial: "fiberglass",
    engineType: "inboard",
    engineBrand: "Yanmar",
    numEngines: 2,
    fuelType: "diesel",
    trailerRequired: false,
    insuranceExpiry: "2026-06-30",
    status: "IN_WATER",
    currentLocationCode: "WB-B03",
    notes: "Charter vessel. Insurance renewal due June 30.",
    createdAt: "2020-08-10T08:00:00Z",
  },
  {
    id: "boat-004",
    ownerId: "cust-002",
    ownerName: "Samui Blue Horizon Charter Co.",
    name: "Blue Horizon I",
    boatType: "MOTOR_YACHT",
    usageType: "charter",
    brand: "Azimut",
    model: "55",
    yearBuilt: 2019,
    registrationNumber: "TH-KS-2020-089",
    hin: "AZI55BH12019",
    flag: "Thailand",
    loaFt: 55.0,
    beamFt: 15.8,
    draftFt: 4.8,
    weightT: 21.0,
    hullMaterial: "fiberglass",
    engineType: "inboard",
    engineBrand: "IPS Volvo",
    numEngines: 2,
    fuelType: "diesel",
    trailerRequired: false,
    insuranceExpiry: "2026-09-15",
    status: "IN_REPAIR",
    currentLocationCode: "RY-01",
    specialHandling: "Engine overhaul zone — no unauthorized access. Confirm with yard manager before moving.",
    notes: "Engine overhaul in progress. ETA: 2 weeks.",
    createdAt: "2020-08-10T08:00:00Z",
  },
  {
    id: "boat-005",
    ownerId: "cust-003",
    ownerName: "Sopida Charoenwong",
    name: "Manta Ray",
    boatType: "SPEED_BOAT",
    usageType: "private",
    brand: "Chaparral",
    model: "270 Signature",
    yearBuilt: 2021,
    registrationNumber: "TH-KS-2022-055",
    hin: "CHP270MR2021",
    flag: "Thailand",
    loaFt: 27.0,
    beamFt: 8.5,
    draftFt: 2.1,
    weightT: 2.8,
    hullMaterial: "fiberglass",
    engineType: "inboard",
    engineBrand: "Mercruiser",
    numEngines: 1,
    fuelType: "gasoline",
    trailerRequired: true,
    insuranceExpiry: "2027-02-28",
    status: "IN_STORAGE",
    currentLocationCode: "DS-A12",
    notes: "Seasonal storage. Owner uses weekends only.",
    createdAt: "2022-11-20T08:00:00Z",
  },
  {
    id: "boat-006",
    ownerId: "cust-004",
    ownerName: "Erik Lindström",
    name: "Nordic Star",
    boatType: "SAILING_YACHT",
    usageType: "private",
    brand: "Hallberg-Rassy",
    model: "43",
    yearBuilt: 2012,
    registrationNumber: "SE-2012-HR43",
    hin: "HR43NS122012",
    flag: "Sweden",
    loaFt: 44.0,
    beamFt: 13.5,
    draftFt: 6.7,
    weightT: 12.5,
    hullMaterial: "fiberglass",
    engineType: "inboard",
    engineBrand: "Volvo Penta",
    numEngines: 1,
    fuelType: "diesel",
    trailerRequired: false,
    insuranceExpiry: "2026-07-10",
    status: "IN_WATER",
    currentLocationCode: "WB-A05",
    notes: "Swedish registration. Antifouling due May 2026.",
    createdAt: "2023-01-10T08:00:00Z",
  },
  {
    id: "boat-007",
    ownerId: "cust-005",
    ownerName: "Samui Fast Boat Services",
    name: "Speedway 1",
    boatType: "SPEED_BOAT",
    usageType: "speedboat_service",
    brand: "Custom Thai Builder",
    model: "32ft Longtail Speed",
    yearBuilt: 2019,
    registrationNumber: "TH-KS-2019-201",
    hin: null,
    flag: "Thailand",
    loaFt: 32.0,
    beamFt: 7.5,
    draftFt: 1.8,
    weightT: 2.2,
    hullMaterial: "fiberglass",
    engineType: "outboard",
    engineBrand: "Yamaha",
    numEngines: 3,
    fuelType: "gasoline",
    trailerRequired: true,
    insuranceExpiry: "2026-12-31",
    status: "IN_WATER",
    currentLocationCode: "WB-C01",
    notes: "Daily use for passenger transfers.",
    createdAt: "2021-06-01T08:00:00Z",
  },
]

// ─── Hardstand / Boat Yard Slots ─────────────────────────────────────────────
// Based on real yard layout:
//   C1-C9  = Concrete floor hardstand, max 41 ft
//   W1-W3  = Wash area, max 26 ft
//   W4     = Wash area, max 51 ft (short-period only)
//   B1-B2  = Beach area, max 60 ft
export const mockBerths = [
  // ── Concrete Hardstand C1-C9 ──────────────────────────────────────────────
  {
    id: "slot-c01", berthCode: "C1", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Unnamed Sloop", customerName: "Alexander", contractType: "long_term", trailerType: "boat_stand", checkIn: "2025-09-01", checkOut: null },
  },
  {
    id: "slot-c02", berthCode: "C2", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "AVAILABLE", shortPeriodOnly: false, currentOccupant: null,
  },
  {
    id: "slot-c03", berthCode: "C3", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "AVAILABLE", shortPeriodOnly: false, currentOccupant: null,
  },
  {
    id: "slot-c04", berthCode: "C4", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Speed Cat", customerName: "Go Ocean Tours", contractType: "repair", trailerType: "company_trailer", checkIn: "2025-11-20", checkOut: "2025-11-30" },
  },
  {
    id: "slot-c05", berthCode: "C5", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "RESERVED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Princess v42", customerName: "Happy Speed Boat For You", contractType: "short_term", trailerType: "company_trailer", checkIn: "2025-12-01", checkOut: "2025-12-07" },
  },
  {
    id: "slot-c06", berthCode: "C6", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Ermerlanda", customerName: "Ermerlanda", contractType: "repair", trailerType: "boat_stand", checkIn: "2025-11-01", checkOut: null },
  },
  {
    id: "slot-c07", berthCode: "C7", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Playboy", customerName: "Playboy", contractType: "repair", trailerType: "boat_stand", checkIn: "2025-11-01", checkOut: "2025-12-26" },
  },
  {
    id: "slot-c08", berthCode: "C8", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Uncle's Boat", customerName: "Uncle", contractType: "monthly", trailerType: "own_trailer", checkIn: "2025-12-01", checkOut: null },
  },
  {
    id: "slot-c09", berthCode: "C9", berthType: "dry", zone: "C", maxLoaFt: 41,
    locationName: "Concrete Hardstand", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Golden Hipppo", customerName: "Golden Hipppo Co.", contractType: "monthly", trailerType: "own_trailer", checkIn: "2025-12-01", checkOut: null },
  },
  // ── Wash Area W1-W4 ─────────────────────────────────────────────────────────
  {
    id: "slot-w01", berthCode: "W1", berthType: "dry", zone: "W", maxLoaFt: 26,
    locationName: "Wash Area", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Dima's Speedboat", customerName: "Dima", contractType: "monthly", trailerType: "own_trailer", checkIn: "2025-12-01", checkOut: null },
  },
  {
    id: "slot-w02", berthCode: "W2", berthType: "dry", zone: "W", maxLoaFt: 26,
    locationName: "Wash Area", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Oliver's Boat", customerName: "Oliver", contractType: "monthly", trailerType: "own_trailer", checkIn: "2025-12-01", checkOut: null },
  },
  {
    id: "slot-w03", berthCode: "W3", berthType: "dry", zone: "W", maxLoaFt: 26,
    locationName: "Wash Area", surfaceType: "concrete",
    status: "OCCUPIED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Golden Hipppo II", customerName: "Golden Hipppo Co.", contractType: "monthly", trailerType: "own_trailer", checkIn: "2025-12-01", checkOut: null },
  },
  {
    id: "slot-w04", berthCode: "W4", berthType: "dry", zone: "W", maxLoaFt: 51,
    locationName: "Wash Area", surfaceType: "concrete",
    status: "AVAILABLE", shortPeriodOnly: true, currentOccupant: null,
    notes: "Short period only — max 7 days",
  },
  // ── Beach Area B1-B2 ────────────────────────────────────────────────────────
  {
    id: "slot-b01", berthCode: "B1", berthType: "dry", zone: "B", maxLoaFt: 60,
    locationName: "Beach Area", surfaceType: "sand/grass",
    status: "RESERVED", shortPeriodOnly: false,
    currentOccupant: { boatName: "Latitude 8 Catamaran", customerName: "Elizabeth", contractType: "long_term", trailerType: "boat_stand", checkIn: "2025-12-14", checkOut: null },
  },
  {
    id: "slot-b02", berthCode: "B2", berthType: "dry", zone: "B", maxLoaFt: 60,
    locationName: "Beach Area", surfaceType: "sand/grass",
    status: "AVAILABLE", shortPeriodOnly: false, currentOccupant: null,
  },
]

// ─── Slot occupancy history (for timeline/calendar view) ────────────────────
export const mockSlotHistory: Record<string, Array<{
  id: string; boatName: string; customerName: string; contractType: string
  trailerType: string; checkIn: string; checkOut: string | null; notes: string
}>> = {
  "slot-c01": [
    { id: "sh-c01-1", boatName: "Unnamed Sloop", customerName: "Alexander", contractType: "long_term", trailerType: "boat_stand", checkIn: "2025-09-01", checkOut: null, notes: "Long-term storage contract" },
  ],
  "slot-c04": [
    { id: "sh-c04-1", boatName: "Speed Cat",  customerName: "Go Ocean Tours", contractType: "repair", trailerType: "company_trailer", checkIn: "2025-11-20", checkOut: "2025-11-30", notes: "Antifouling + engine service" },
    { id: "sh-c04-2", boatName: "Nimbus 11",  customerName: "Go Ocean Tours", contractType: "repair", trailerType: "company_trailer", checkIn: "2025-12-14", checkOut: null, notes: "Arriving Dec 14 for full survey" },
  ],
  "slot-c06": [
    { id: "sh-c06-1", boatName: "Ermerlanda", customerName: "Ermerlanda", contractType: "repair", trailerType: "boat_stand", checkIn: "2025-11-01", checkOut: null, notes: "Full hull repaint + engine overhaul" },
  ],
  "slot-c07": [
    { id: "sh-c07-1", boatName: "Playboy",    customerName: "Playboy", contractType: "repair", trailerType: "boat_stand", checkIn: "2025-11-01", checkOut: "2025-12-26", notes: "Annual maintenance" },
  ],
}

export const mockQuotations = [
  {
    id: "quot-001",
    quoteNumber: "QT-2026-0041",
    customerId: "cust-001",
    customerName: "James Thornton",
    boatId: "boat-001",
    boatName: "Sea Hawk",
    status: "SENT",
    totalAmount: 49199,
    validUntil: "2026-06-15",
    createdAt: "2026-05-10T09:00:00Z",
    itemCount: 4,
  },
  {
    id: "quot-002",
    quoteNumber: "QT-2026-0040",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co.",
    boatId: "boat-004",
    boatName: "Blue Horizon I",
    status: "ACCEPTED",
    totalAmount: 380964,
    validUntil: "2026-05-31",
    createdAt: "2026-05-02T10:30:00Z",
    itemCount: 7,
  },
  {
    id: "quot-003",
    quoteNumber: "QT-2026-0039",
    customerId: "cust-004",
    customerName: "Erik Lindström",
    boatId: "boat-006",
    boatName: "Nordic Star",
    status: "DRAFT",
    totalAmount: 77040,
    validUntil: "2026-06-10",
    createdAt: "2026-05-15T14:00:00Z",
    itemCount: 3,
  },
  {
    id: "quot-004",
    quoteNumber: "QT-2026-0038",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co.",
    boatId: "boat-003",
    boatName: "Blue Dream",
    status: "CONVERTED",
    totalAmount: 166920,
    validUntil: "2026-05-01",
    createdAt: "2026-04-18T08:00:00Z",
    itemCount: 3,
  },
]

// ─── Quotation line items (keyed by quotationId) ─────────────────────────────
export const mockQuotationItems: Record<string, Array<{
  id: string; description: string; category: string; unit: string
  qty: number; unitPrice: number; amount: number; laborCost: number; materialCost: number
}>> = {
  "quot-001": [
    { id: "qi-001-1", description: "AC system full service — 3 units",        category: "Air Conditioning", unit: "unit", qty: 3,  unitPrice: 8500,  amount: 25500,  laborCost: 12000, materialCost: 13500 },
    { id: "qi-001-2", description: "Refrigerant top-up R-410A",               category: "Air Conditioning", unit: "kg",   qty: 2,  unitPrice: 1200,  amount: 2400,   laborCost: 0,     materialCost: 2400  },
    { id: "qi-001-3", description: "Navigation system calibration",            category: "Electrical",       unit: "job",  qty: 1,  unitPrice: 8500,  amount: 8500,   laborCost: 6000,  materialCost: 2500  },
    { id: "qi-001-4", description: "Engine room bilge pump replacement",       category: "Engine",           unit: "pc",   qty: 1,  unitPrice: 12000, amount: 12000,  laborCost: 4000,  materialCost: 8000  },
  ],
  "quot-002": [
    { id: "qi-002-1", description: "Port engine overhaul — full disassembly",  category: "Engine",           unit: "job",  qty: 1,  unitPrice: 180000,amount: 180000, laborCost: 80000, materialCost: 100000},
    { id: "qi-002-2", description: "Starboard engine service & inspection",    category: "Engine",           unit: "job",  qty: 1,  unitPrice: 45000, amount: 45000,  laborCost: 20000, materialCost: 25000 },
    { id: "qi-002-3", description: "Engine parts: gaskets, seals, impeller",   category: "Engine",           unit: "set",  qty: 1,  unitPrice: 85000, amount: 85000,  laborCost: 0,     materialCost: 85000 },
    { id: "qi-002-4", description: "Labour — senior mechanic (40 hrs)",        category: "Engine",           unit: "hr",   qty: 40, unitPrice: 800,   amount: 32000,  laborCost: 32000, materialCost: 0     },
    { id: "qi-002-5", description: "Cooling system flush & inspection",        category: "Engine",           unit: "job",  qty: 1,  unitPrice: 18000, amount: 18000,  laborCost: 8000,  materialCost: 10000 },
    { id: "qi-002-6", description: "Sea trial & commissioning",                category: "Engine",           unit: "job",  qty: 1,  unitPrice: 15000, amount: 15000,  laborCost: 15000, materialCost: 0     },
    { id: "qi-002-7", description: "Fuel system inspection",                   category: "Engine",           unit: "job",  qty: 1,  unitPrice: 12000, amount: 12000,  laborCost: 8000,  materialCost: 4000  },
  ],
  "quot-003": [
    { id: "qi-003-1", description: "Full hull antifouling — Jotun SeaQuantum", category: "Antifouling",      unit: "job",  qty: 1,  unitPrice: 55000, amount: 55000,  laborCost: 20000, materialCost: 35000 },
    { id: "qi-003-2", description: "Hull surface prep & pressure wash",        category: "Antifouling",      unit: "job",  qty: 1,  unitPrice: 8000,  amount: 8000,   laborCost: 6000,  materialCost: 2000  },
    { id: "qi-003-3", description: "Haul-out, block, and relaunch (5 days)",   category: "Other",            unit: "day",  qty: 5,  unitPrice: 1800,  amount: 9000,   laborCost: 5000,  materialCost: 4000  },
  ],
  "quot-004": [
    { id: "qi-004-1", description: "Annual wet berth — WB-B03 (Jan–Dec 2026)", category: "Berth Fee",        unit: "year", qty: 1,  unitPrice: 120000,amount: 120000, laborCost: 0,     materialCost: 0     },
    { id: "qi-004-2", description: "Electricity & water utility (est. Q1-Q4)", category: "Utility",          unit: "year", qty: 1,  unitPrice: 28000, amount: 28000,  laborCost: 0,     materialCost: 0     },
    { id: "qi-004-3", description: "Security & maintenance levy",              category: "Utility",          unit: "year", qty: 1,  unitPrice: 8000,  amount: 8000,   laborCost: 0,     materialCost: 0     },
  ],
}

// ─── Quotation totals (keyed by quotationId) ───────────────────────────────────
export const mockQuotationTotals: Record<string, {
  subtotal: number; discountType: string; discountValue: number; discountAmount: number
  taxRate: number; taxAmount: number; grandTotal: number; depositRequired: number
  internalCost: number; grossMargin: number
}> = {
  "quot-001": { subtotal: 48400,  discountType: "PERCENT", discountValue: 5,  discountAmount: 2420,  taxRate: 7, taxAmount: 3219,  grandTotal: 49199,  depositRequired: 25000,  internalCost: 28000, grossMargin: 42 },
  "quot-002": { subtotal: 387000, discountType: "PERCENT", discountValue: 8,  discountAmount: 30960, taxRate: 7, taxAmount: 24924, grandTotal: 380964, depositRequired: 150000, internalCost: 255000, grossMargin: 33 },
  "quot-003": { subtotal: 72000,  discountType: "NONE",    discountValue: 0,  discountAmount: 0,     taxRate: 7, taxAmount: 5040,  grandTotal: 77040,  depositRequired: 35000,  internalCost: 42000, grossMargin: 42 },
  "quot-004": { subtotal: 156000, discountType: "NONE",    discountValue: 0,  discountAmount: 0,     taxRate: 7, taxAmount: 10920, grandTotal: 166920, depositRequired: 60000,  internalCost: 0, grossMargin: 100 },
}

export const mockInvoices = [
  {
    id: "inv-001",
    invoiceNumber: "INV-2026-0088",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co.",
    boatId: "boat-004",
    boatName: "Blue Horizon I",
    status: "PARTIALLY_PAID",
    totalAmount: 419440,
    paidAmount: 234000,
    outstandingBalance: 185440,
    dueDate: "2026-05-31",
    createdAt: "2026-05-05T10:00:00Z",
  },
  {
    id: "inv-002",
    invoiceNumber: "INV-2026-0085",
    customerId: "cust-001",
    customerName: "James Thornton",
    boatId: "boat-001",
    boatName: "Sea Hawk",
    status: "ISSUED",
    totalAmount: 31779,
    paidAmount: 0,
    outstandingBalance: 31779,
    dueDate: "2026-06-05",
    createdAt: "2026-05-06T09:00:00Z",
  },
  {
    id: "inv-003",
    invoiceNumber: "INV-2026-0082",
    customerId: "cust-004",
    customerName: "Erik Lindström",
    boatId: "boat-006",
    boatName: "Nordic Star",
    status: "ISSUED",
    totalAmount: 29425,
    paidAmount: 0,
    outstandingBalance: 29425,
    dueDate: "2026-06-01",
    createdAt: "2026-05-02T11:00:00Z",
  },
  {
    id: "inv-004",
    invoiceNumber: "INV-2026-0078",
    customerId: "cust-003",
    customerName: "Sopida Charoenwong",
    boatId: "boat-005",
    boatName: "Manta Ray",
    status: "PAID",
    totalAmount: 23326,
    paidAmount: 23326,
    outstandingBalance: 0,
    dueDate: "2026-04-30",
    createdAt: "2026-04-15T14:00:00Z",
  },
  {
    id: "inv-005",
    invoiceNumber: "INV-2026-0075",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co.",
    boatId: "boat-003",
    boatName: "Blue Dream",
    status: "OVERDUE",
    totalAmount: 166920,
    paidAmount: 0,
    outstandingBalance: 166920,
    dueDate: "2026-04-30",
    createdAt: "2026-04-01T08:00:00Z",
  },
]

// ─── Invoice line items (keyed by invoiceId) ──────────────────────────────────
export const mockInvoiceItems: Record<string, Array<{
  id: string; description: string; unit: string; qty: number; unitPrice: number; amount: number
}>> = {
  "inv-001": [
    { id: "ii-001-1", description: "Port engine overhaul — complete disassembly & rebuild", unit: "job",  qty: 1,   unitPrice: 280000, amount: 280000 },
    { id: "ii-001-2", description: "Engine parts & consumables (gaskets, seals, impeller)", unit: "set",  qty: 1,   unitPrice: 85000,  amount: 85000  },
    { id: "ii-001-3", description: "Labour — senior mechanic (40 hrs)",                      unit: "hr",   qty: 40,  unitPrice: 800,    amount: 32000  },
    { id: "ii-001-4", description: "Sea trial & final commissioning",                         unit: "job",  qty: 1,   unitPrice: 15000,  amount: 15000  },
  ],
  "inv-002": [
    { id: "ii-002-1", description: "Air conditioning service — 3 units",                     unit: "unit", qty: 3,   unitPrice: 8500,   amount: 25500  },
    { id: "ii-002-2", description: "AC refrigerant top-up (R-410A)",                         unit: "kg",   qty: 2,   unitPrice: 1200,   amount: 2400   },
    { id: "ii-002-3", description: "Filter replacement & cleaning",                           unit: "set",  qty: 1,   unitPrice: 1800,   amount: 1800   },
  ],
  "inv-003": [
    { id: "ii-003-1", description: "Antifouling paint — full hull (Jotun SeaQuantum)",       unit: "job",  qty: 1,   unitPrice: 18000,  amount: 18000  },
    { id: "ii-003-2", description: "Hull wash & surface preparation",                         unit: "job",  qty: 1,   unitPrice: 4500,   amount: 4500   },
    { id: "ii-003-3", description: "Waterline tape & masking",                                unit: "job",  qty: 1,   unitPrice: 2000,   amount: 2000   },
    { id: "ii-003-4", description: "Haul-out & block fee (3 days)",                           unit: "day",  qty: 3,   unitPrice: 1000,   amount: 3000   },
  ],
  "inv-004": [
    { id: "ii-004-1", description: "Navigation light replacement (bow/stern/masthead)",        unit: "set",  qty: 1,   unitPrice: 12000,  amount: 12000  },
    { id: "ii-004-2", description: "Wiring inspection & cable routing",                       unit: "hr",   qty: 8,   unitPrice: 700,    amount: 5600   },
    { id: "ii-004-3", description: "Shore power socket replacement",                           unit: "pc",   qty: 1,   unitPrice: 4200,   amount: 4200   },
  ],
  "inv-005": [
    { id: "ii-005-1", description: "Annual wet berth fee — Blue Dream (Jan–Dec 2026)",        unit: "year", qty: 1,   unitPrice: 120000, amount: 120000 },
    { id: "ii-005-2", description: "Utility charges (electric + water) Q1 2026",              unit: "qtr",  qty: 1,   unitPrice: 28000,  amount: 28000  },
    { id: "ii-005-3", description: "Security & maintenance levy",                              unit: "year", qty: 1,   unitPrice: 8000,   amount: 8000   },
  ],
}

// ─── Invoice VAT / totals ─────────────────────────────────────────────────────
export const mockInvoiceTotals: Record<string, {
  subtotal: number; discountAmount: number; taxRate: number; taxAmount: number; grandTotal: number
}> = {
  "inv-001": { subtotal: 412000, discountAmount: 20000, taxRate: 7, taxAmount: 27440, grandTotal: 419440 },
  "inv-002": { subtotal: 29700,  discountAmount: 0,     taxRate: 7, taxAmount: 2079,  grandTotal: 31779  },
  "inv-003": { subtotal: 27500,  discountAmount: 0,     taxRate: 7, taxAmount: 1925,  grandTotal: 29425  },
  "inv-004": { subtotal: 21800,  discountAmount: 0,     taxRate: 7, taxAmount: 1526,  grandTotal: 23326  },
  "inv-005": { subtotal: 156000, discountAmount: 0,     taxRate: 7, taxAmount: 10920, grandTotal: 166920 },
}

// ─── Payment history per invoice ──────────────────────────────────────────────
export const mockInvoicePayments: Record<string, Array<{
  id: string; reference: string; amount: number; method: string; date: string; confirmedBy: string; slipRef: string | null
}>> = {
  "inv-001": [
    { id: "pay-inv001-1", reference: "PAY-2026-088", amount: 234000, method: "BANK_TRANSFER", date: "2026-05-12T10:30:00Z", confirmedBy: "Finance Team", slipRef: "SCB-20260512-001" },
  ],
  "inv-004": [
    { id: "pay-inv004-1", reference: "PAY-2026-078", amount: 23326,  method: "QR_PAYMENT",   date: "2026-04-28T14:00:00Z", confirmedBy: "Finance Team", slipRef: "QR-20260428-085"  },
  ],
}

// ─── Service Requests ─────────────────────────────────────────────────────────
export const mockServiceRequests = [
  {
    id: "sr-001",
    reference: "SR-2026-0041",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co., Ltd.",
    boatId: "boat-004",
    boatName: "Blue Horizon I",
    category: "Engine",
    title: "Engine overhaul — both engines",
    description: "Both Volvo IPS engines making knocking noise at high RPM. Oil pressure warning light on port engine. Request full overhaul and inspection.",
    priority: "HIGH",
    status: "IN_PROGRESS",
    linkedWorkOrderId: "wo-001",
    linkedQuotationId: "quot-002",
    requestedDate: "2026-04-20T08:00:00Z",
    scheduledDate: "2026-04-28T08:00:00Z",
    completedDate: null,
    assignedTo: "Somchai T. (Lead Mechanic)",
    notes: "Customer confirmed engine noise started after last trip to Phangan.",
    createdAt: "2026-04-20T08:15:00Z",
  },
  {
    id: "sr-002",
    reference: "SR-2026-0038",
    customerId: "cust-001",
    customerName: "James Thornton",
    boatId: "boat-001",
    boatName: "Sea Hawk",
    category: "Antifouling",
    title: "Annual antifouling & hull clean",
    description: "Due for annual haul-out. Antifouling paint, hull inspection, propeller polish, and anode replacement.",
    priority: "MEDIUM",
    status: "QUOTATION_SENT",
    linkedWorkOrderId: null,
    linkedQuotationId: "quot-001",
    requestedDate: "2026-05-01T09:00:00Z",
    scheduledDate: null,
    completedDate: null,
    assignedTo: null,
    notes: "Customer prefers International Micron antifouling paint.",
    createdAt: "2026-05-01T09:30:00Z",
  },
  {
    id: "sr-003",
    reference: "SR-2026-0035",
    customerId: "cust-001",
    customerName: "James Thornton",
    boatId: "boat-002",
    boatName: "Night Star",
    category: "Electrical",
    title: "Navigation lights & bilge pump failure",
    description: "Port navigation light not working. Automatic bilge pump not activating. Requires electrical inspection and repair.",
    priority: "MEDIUM",
    status: "INSPECTION_REQUIRED",
    linkedWorkOrderId: null,
    linkedQuotationId: null,
    requestedDate: "2026-05-10T10:00:00Z",
    scheduledDate: "2026-05-20T09:00:00Z",
    completedDate: null,
    assignedTo: "Prasert W. (Electrician)",
    notes: null,
    createdAt: "2026-05-10T10:45:00Z",
  },
  {
    id: "sr-004",
    reference: "SR-2026-0029",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co., Ltd.",
    boatId: "boat-003",
    boatName: "Blue Dream",
    category: "Cleaning / Detailing",
    title: "Post-charter full detail & teak cleaning",
    description: "Full interior and exterior detail after 2-week charter trip. Teak deck cleaning and oiling. Upholstery cleaning.",
    priority: "LOW",
    status: "COMPLETED",
    linkedWorkOrderId: "wo-003",
    linkedQuotationId: null,
    requestedDate: "2026-04-10T08:00:00Z",
    scheduledDate: "2026-04-12T08:00:00Z",
    completedDate: "2026-04-13T16:00:00Z",
    assignedTo: "Cleaning Crew",
    notes: "Completed on schedule. Customer satisfied.",
    createdAt: "2026-04-10T08:30:00Z",
  },
  {
    id: "sr-005",
    reference: "SR-2026-0044",
    customerId: "cust-004",
    customerName: "Erik Lindström",
    boatId: "boat-005",
    boatName: "Speed Demon",
    category: "Fiberglass",
    title: "Gel coat repair — starboard bow impact damage",
    description: "Starboard bow has gel coat cracking and minor impact damage from dock contact. Requires gel coat repair and colour matching.",
    priority: "MEDIUM",
    status: "NEW_REQUEST",
    linkedWorkOrderId: null,
    linkedQuotationId: null,
    requestedDate: "2026-05-16T11:00:00Z",
    scheduledDate: null,
    completedDate: null,
    assignedTo: null,
    notes: "Customer sent photos via LINE. Damage appears superficial — no structural concern.",
    createdAt: "2026-05-16T11:20:00Z",
  },
]

// ─── Work Orders ──────────────────────────────────────────────────────────────
export const mockWorkOrders = [
  {
    id: "wo-001",
    reference: "WO-2026-0041",
    serviceRequestId: "sr-001",
    quotationId: "quot-002",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co., Ltd.",
    boatId: "boat-004",
    boatName: "Blue Horizon I",
    title: "Engine overhaul — both Volvo IPS engines",
    category: "Engine",
    status: "IN_PROGRESS",
    priority: "HIGH",
    startDate: "2026-04-28",
    estimatedEndDate: "2026-05-20",
    actualEndDate: null,
    assignedTo: "Somchai T.",
    contractorName: "Volvo Penta Thailand (contractor)",
    totalRevenue: 420000,
    totalLaborCost: 85000,
    totalMaterialCost: 142000,
    totalContractorCost: 80000,
    progressPercent: 65,
    notes: "Starboard engine parts arrived. Port engine parts due 18 May.",
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "wo-002",
    reference: "WO-2026-0038",
    serviceRequestId: "sr-002",
    quotationId: "quot-001",
    customerId: "cust-001",
    customerName: "James Thornton",
    boatId: "boat-001",
    boatName: "Sea Hawk",
    title: "Annual antifouling & hull service",
    category: "Antifouling",
    status: "WAITING_CUSTOMER_APPROVAL",
    priority: "MEDIUM",
    startDate: null,
    estimatedEndDate: null,
    actualEndDate: null,
    assignedTo: null,
    contractorName: null,
    totalRevenue: 95000,
    totalLaborCost: 25000,
    totalMaterialCost: 18000,
    totalContractorCost: 0,
    progressPercent: 0,
    notes: "Awaiting customer approval on quotation. Haul-out slot held for 22 May.",
    createdAt: "2026-05-02T10:00:00Z",
  },
  {
    id: "wo-003",
    reference: "WO-2026-0029",
    serviceRequestId: "sr-004",
    quotationId: null,
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co., Ltd.",
    boatId: "boat-003",
    boatName: "Blue Dream",
    title: "Post-charter full detail & teak cleaning",
    category: "Cleaning / Detailing",
    status: "COMPLETED",
    priority: "LOW",
    startDate: "2026-04-12",
    estimatedEndDate: "2026-04-13",
    actualEndDate: "2026-04-13",
    assignedTo: "Cleaning Crew",
    contractorName: null,
    totalRevenue: 18500,
    totalLaborCost: 8000,
    totalMaterialCost: 3200,
    totalContractorCost: 0,
    progressPercent: 100,
    notes: "Completed on schedule. Handover photos uploaded.",
    createdAt: "2026-04-10T09:00:00Z",
  },
]

// ─── Work Order Tasks ──────────────────────────────────────────────────────────
export const mockWorkOrderTasks: Record<string, Array<{
  id: string; title: string; category: string; assignedTo: string | null
  status: "TODO" | "IN_PROGRESS" | "WAITING" | "COMPLETED" | "VERIFIED"
  estimatedHours: number; actualHours: number | null; dueDate: string | null; notes: string | null
}>> = {
  "wo-001": [
    { id: "task-001-1", title: "Initial inspection — both engines", category: "Engine", assignedTo: "Somchai T.", status: "COMPLETED", estimatedHours: 4, actualHours: 5, dueDate: "2026-04-28", notes: "Found worn bearings and carbon build-up in combustion chambers." },
    { id: "task-001-2", title: "Disassemble port engine", category: "Engine", assignedTo: "Somchai T.", status: "COMPLETED", estimatedHours: 8, actualHours: 8, dueDate: "2026-04-30", notes: null },
    { id: "task-001-3", title: "Disassemble starboard engine", category: "Engine", assignedTo: "Prasert W.", status: "COMPLETED", estimatedHours: 8, actualHours: 9, dueDate: "2026-04-30", notes: null },
    { id: "task-001-4", title: "Replace bearings & seals — starboard", category: "Engine", assignedTo: "Somchai T.", status: "IN_PROGRESS", estimatedHours: 12, actualHours: null, dueDate: "2026-05-15", notes: "Parts arrived 2026-05-10." },
    { id: "task-001-5", title: "Replace bearings & seals — port", category: "Engine", assignedTo: "Prasert W.", status: "WAITING", estimatedHours: 12, actualHours: null, dueDate: "2026-05-18", notes: "Waiting for parts — ETA 18 May." },
    { id: "task-001-6", title: "Reassemble & test run both engines", category: "Engine", assignedTo: "Somchai T.", status: "TODO", estimatedHours: 6, actualHours: null, dueDate: "2026-05-20", notes: null },
    { id: "task-001-7", title: "Volvo Penta contractor sea trial", category: "Engine", assignedTo: "Volvo Penta TH", status: "TODO", estimatedHours: 4, actualHours: null, dueDate: "2026-05-21", notes: null },
  ],
  "wo-002": [
    { id: "task-002-1", title: "Haul-out & pressure wash", category: "Antifouling", assignedTo: null, status: "TODO", estimatedHours: 3, actualHours: null, dueDate: "2026-05-22", notes: null },
    { id: "task-002-2", title: "Hull inspection & osmotic blister check", category: "Antifouling", assignedTo: null, status: "TODO", estimatedHours: 2, actualHours: null, dueDate: "2026-05-22", notes: null },
    { id: "task-002-3", title: "Antifouling paint — 2 coats", category: "Antifouling", assignedTo: null, status: "TODO", estimatedHours: 8, actualHours: null, dueDate: "2026-05-23", notes: null },
    { id: "task-002-4", title: "Propeller polish & anode replacement", category: "Antifouling", assignedTo: null, status: "TODO", estimatedHours: 3, actualHours: null, dueDate: "2026-05-24", notes: null },
    { id: "task-002-5", title: "Launch & sea trial", category: "Antifouling", assignedTo: null, status: "TODO", estimatedHours: 2, actualHours: null, dueDate: "2026-05-24", notes: null },
  ],
  "wo-003": [
    { id: "task-003-1", title: "Exterior wash & wax", category: "Cleaning", assignedTo: "Cleaning Crew", status: "VERIFIED", estimatedHours: 4, actualHours: 4, dueDate: "2026-04-12", notes: null },
    { id: "task-003-2", title: "Interior full clean & vacuum", category: "Cleaning", assignedTo: "Cleaning Crew", status: "VERIFIED", estimatedHours: 6, actualHours: 7, dueDate: "2026-04-12", notes: null },
    { id: "task-003-3", title: "Teak deck clean & oil", category: "Cleaning", assignedTo: "Cleaning Crew", status: "VERIFIED", estimatedHours: 5, actualHours: 5, dueDate: "2026-04-13", notes: null },
    { id: "task-003-4", title: "Upholstery clean", category: "Cleaning", assignedTo: "Cleaning Crew", status: "VERIFIED", estimatedHours: 3, actualHours: 3, dueDate: "2026-04-13", notes: null },
  ],
}

// ─── Work Order Materials ─────────────────────────────────────────────────────
export const mockWorkOrderMaterials: Record<string, Array<{
  id: string; itemName: string; unit: string; qty: number; unitCost: number; totalCost: number
  chargeToCustomer: boolean; sellingPrice: number; supplier: string | null
}>> = {
  "wo-001": [
    { id: "mat-001-1", itemName: "Volvo IPS bearing set (port)", unit: "set", qty: 1, unitCost: 28000, totalCost: 28000, chargeToCustomer: true, sellingPrice: 35000, supplier: "Volvo Penta Thailand" },
    { id: "mat-001-2", itemName: "Volvo IPS bearing set (starboard)", unit: "set", qty: 1, unitCost: 28000, totalCost: 28000, chargeToCustomer: true, sellingPrice: 35000, supplier: "Volvo Penta Thailand" },
    { id: "mat-001-3", itemName: "Engine seal kit", unit: "set", qty: 2, unitCost: 8500, totalCost: 17000, chargeToCustomer: true, sellingPrice: 11000, supplier: "Volvo Penta Thailand" },
    { id: "mat-001-4", itemName: "Engine oil 15W-40 (20L)", unit: "drum", qty: 4, unitCost: 2800, totalCost: 11200, chargeToCustomer: true, sellingPrice: 3500, supplier: "PTT" },
    { id: "mat-001-5", itemName: "Engine coolant", unit: "L", qty: 20, unitCost: 180, totalCost: 3600, chargeToCustomer: true, sellingPrice: 240, supplier: "Local supplier" },
    { id: "mat-001-6", itemName: "Shop consumables", unit: "lot", qty: 1, unitCost: 4200, totalCost: 4200, chargeToCustomer: false, sellingPrice: 0, supplier: null },
  ],
  "wo-002": [
    { id: "mat-002-1", itemName: "International Micron antifouling (4L)", unit: "tin", qty: 6, unitCost: 2800, totalCost: 16800, chargeToCustomer: true, sellingPrice: 3500, supplier: "International Paints TH" },
    { id: "mat-002-2", itemName: "Zinc anode set", unit: "set", qty: 1, unitCost: 1200, totalCost: 1200, chargeToCustomer: true, sellingPrice: 1500, supplier: "Marine Parts KS" },
  ],
  "wo-003": [
    { id: "mat-003-1", itemName: "Teak cleaner", unit: "L", qty: 5, unitCost: 350, totalCost: 1750, chargeToCustomer: true, sellingPrice: 450, supplier: "Boat Care TH" },
    { id: "mat-003-2", itemName: "Teak oil", unit: "L", qty: 3, unitCost: 480, totalCost: 1440, chargeToCustomer: true, sellingPrice: 600, supplier: "Boat Care TH" },
  ],
}

// ─── Work Order Photos ─────────────────────────────────────────────────────────
export const mockWorkOrderPhotos: Record<string, Array<{
  id: string; category: "BEFORE" | "DURING" | "AFTER" | "DEFECT" | "EVIDENCE" | "COMPLETION"
  caption: string; uploadedBy: string; uploadedAt: string; url: string
}>> = {
  "wo-001": [
    { id: "ph-001-1", category: "BEFORE",   caption: "Port engine before disassembly",        uploadedBy: "Somchai T.",   uploadedAt: "2026-04-28T09:00:00Z", url: "/placeholder/400/300" },
    { id: "ph-001-2", category: "BEFORE",   caption: "Starboard engine before disassembly",   uploadedBy: "Somchai T.",   uploadedAt: "2026-04-28T09:05:00Z", url: "/placeholder/400/300" },
    { id: "ph-001-3", category: "DEFECT",   caption: "Worn bearing — port engine",            uploadedBy: "Somchai T.",   uploadedAt: "2026-04-29T11:30:00Z", url: "/placeholder/400/300" },
    { id: "ph-001-4", category: "DEFECT",   caption: "Carbon build-up combustion chamber",    uploadedBy: "Prasert W.",   uploadedAt: "2026-04-30T10:00:00Z", url: "/placeholder/400/300" },
    { id: "ph-001-5", category: "DURING",   caption: "Starboard engine — new bearings fitted",uploadedBy: "Somchai T.",   uploadedAt: "2026-05-12T14:00:00Z", url: "/placeholder/400/300" },
  ],
  "wo-003": [
    { id: "ph-003-1", category: "BEFORE",   caption: "Teak deck — before cleaning",          uploadedBy: "Cleaning Crew", uploadedAt: "2026-04-12T08:15:00Z", url: "/placeholder/400/300" },
    { id: "ph-003-2", category: "AFTER",    caption: "Teak deck — after cleaning & oil",     uploadedBy: "Cleaning Crew", uploadedAt: "2026-04-13T15:30:00Z", url: "/placeholder/400/300" },
    { id: "ph-003-3", category: "COMPLETION", caption: "Final handover — Blue Dream",        uploadedBy: "Cleaning Crew", uploadedAt: "2026-04-13T16:00:00Z", url: "/placeholder/400/300" },
  ],
}

// ─── Ramp Bookings ────────────────────────────────────────────────────────────
export const mockRampBookings = [
  {
    id: "rb-001",
    reference: "RB-2026-0019",
    customerId: "cust-001",
    customerName: "James Thornton",
    boatId: "boat-002",
    boatName: "Night Star",
    operationType: "RETRIEVAL",
    status: "CONFIRMED",
    requestedDate: "2026-05-22",
    requestedTime: "08:00",
    confirmedTime: "08:30",
    boatDraftFt: 6.2,
    trailerHeightFt: 2.0,
    safetyClearanceFt: 1.5,
    rampDepthOffsetM: -1.0,
    requiredTideM: 1.31,
    isTideSafe: true,
    assignedStaff: "Operation Team A",
    trailerRef: "TR-03",
    notes: "Mast needs separate handling — contact rigging team.",
    createdAt: "2026-05-19T10:00:00Z",
  },
  {
    id: "rb-002",
    reference: "RB-2026-0018",
    customerId: "cust-003",
    customerName: "Sopida Charoenwong",
    boatId: "boat-005",
    boatName: "Speed Demon",
    operationType: "LAUNCH",
    status: "COMPLETED",
    requestedDate: "2026-05-15",
    requestedTime: "10:00",
    confirmedTime: "10:00",
    boatDraftFt: 1.8,
    trailerHeightFt: 1.5,
    safetyClearanceFt: 1.0,
    rampDepthOffsetM: -1.0,
    requiredTideM: 0.42,
    isTideSafe: true,
    assignedStaff: "Operation Team B",
    trailerRef: "TR-01",
    notes: null,
    createdAt: "2026-05-14T09:00:00Z",
  },
  {
    id: "rb-003",
    reference: "RB-2026-0020",
    customerId: "cust-002",
    customerName: "Samui Blue Horizon Charter Co., Ltd.",
    boatId: "boat-003",
    boatName: "Blue Dream",
    operationType: "LAUNCH",
    status: "REQUESTED",
    requestedDate: "2026-05-25",
    requestedTime: null,
    confirmedTime: null,
    boatDraftFt: 3.9,
    trailerHeightFt: 2.5,
    safetyClearanceFt: 1.5,
    rampDepthOffsetM: -1.0,
    requiredTideM: 1.59,
    isTideSafe: null,
    assignedStaff: null,
    trailerRef: null,
    notes: "Catamaran — needs wide trailer TR-04.",
    createdAt: "2026-05-19T14:00:00Z",
  },
]

// ─── Sample tide data for tide calculator (Ko Samui, 22 May 2026) ─────────────
export const mockTideData: Record<string, Array<{ time: string; heightM: number }>> = {
  "2026-05-22": [
    { time: "00:00", heightM: 0.82 }, { time: "01:00", heightM: 1.04 },
    { time: "02:00", heightM: 1.21 }, { time: "03:00", heightM: 1.31 },
    { time: "04:00", heightM: 1.28 }, { time: "05:00", heightM: 1.12 },
    { time: "06:00", heightM: 0.87 }, { time: "07:00", heightM: 0.56 },
    { time: "08:00", heightM: 0.28 }, { time: "09:00", heightM: 0.12 },
    { time: "10:00", heightM: 0.14 }, { time: "11:00", heightM: 0.34 },
    { time: "12:00", heightM: 0.64 }, { time: "13:00", heightM: 0.96 },
    { time: "14:00", heightM: 1.22 }, { time: "15:00", heightM: 1.35 },
    { time: "16:00", heightM: 1.30 }, { time: "17:00", heightM: 1.08 },
    { time: "18:00", heightM: 0.72 }, { time: "19:00", heightM: 0.38 },
    { time: "20:00", heightM: 0.16 }, { time: "21:00", heightM: 0.18 },
    { time: "22:00", heightM: 0.42 }, { time: "23:00", heightM: 0.72 },
  ],
  "2026-05-25": [
    { time: "00:00", heightM: 0.68 }, { time: "01:00", heightM: 0.95 },
    { time: "02:00", heightM: 1.18 }, { time: "03:00", heightM: 1.32 },
    { time: "04:00", heightM: 1.34 }, { time: "05:00", heightM: 1.22 },
    { time: "06:00", heightM: 0.98 }, { time: "07:00", heightM: 0.68 },
    { time: "08:00", heightM: 0.40 }, { time: "09:00", heightM: 0.22 },
    { time: "10:00", heightM: 0.20 }, { time: "11:00", heightM: 0.36 },
    { time: "12:00", heightM: 0.62 }, { time: "13:00", heightM: 0.91 },
    { time: "14:00", heightM: 1.15 }, { time: "15:00", heightM: 1.28 },
    { time: "16:00", heightM: 1.28 }, { time: "17:00", heightM: 1.14 },
    { time: "18:00", heightM: 0.88 }, { time: "19:00", heightM: 0.60 },
    { time: "20:00", heightM: 0.40 }, { time: "21:00", heightM: 0.32 },
    { time: "22:00", heightM: 0.40 }, { time: "23:00", heightM: 0.58 },
  ],
}

export const mockDashboardStats = {
  totalRevenueThisMonth: 2450000,
  revenueChangePercent: 12.4,
  activeCustomers: 47,
  customersChangePercent: 5.2,
  boatsInYard: 12,
  boatsInYardChange: 2,
  openQuotations: 8,
  openQuotationsValue: 1240000,
  wetBerthOccupancy: 78,
  dryStorageOccupancy: 65,
  outstandingInvoices: 485000,
  overdueInvoices: 156000,
  overdueCount: 1,
  jobsThisMonth: 23,
  jobsCompleted: 18,
}

export const mockRecentActivity = [
  { id: 1, type: "quotation", message: "Quotation QT-2026-0041 sent to James Thornton", time: "2 hours ago", icon: "FileText" },
  { id: 2, type: "payment", message: "Payment of ฿234,000 received from Blue Horizon Charter", time: "5 hours ago", icon: "CreditCard" },
  { id: 3, type: "boat", message: "Blue Horizon I moved to Repair Yard RY-01", time: "Yesterday", icon: "Anchor" },
  { id: 4, type: "invoice", message: "Invoice INV-2026-0088 created for ฿420,000", time: "2 days ago", icon: "Receipt" },
  { id: 5, type: "customer", message: "New customer registered: Erik Lindström", time: "3 days ago", icon: "User" },
  { id: 6, type: "quotation", message: "Quotation QT-2026-0040 accepted by Blue Horizon Charter", time: "4 days ago", icon: "CheckCircle" },
]
