BEGIN;

CREATE TABLE IF NOT EXISTS public.mms_tide_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  hour smallint NOT NULL,
  tide_m numeric(4,2) NOT NULL,
  source text NOT NULL DEFAULT 'Ko Samui tide table 2026 PDF',
  CONSTRAINT mms_tide_records_hour_check CHECK (hour BETWEEN 0 AND 23),
  CONSTRAINT mms_tide_records_date_hour_unique UNIQUE (date, hour)
);

CREATE INDEX IF NOT EXISTS mms_tide_records_date_idx
  ON public.mms_tide_records (date);

ALTER TABLE public.mms_tide_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.mms_tide_records FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.mms_tide_records TO service_role;

COMMENT ON TABLE public.mms_tide_records IS
  'Hourly Ko Samui tide heights used by server-side ramp safety calculations.';

NOTIFY pgrst, 'reload schema';

COMMIT;
